const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
const SET_SELECT_VALUE = 'SET_SELECT_VALUE';
const SET_SELECT_CATEGORIES = 'SET_SELECT_CATEGORIES';
const RECEIVED_ITEMS = 'RECEIVED_ITEMS';
const LOAD_MORE_ITEMS = 'LOAD_MORE_ITEMS';

export {
    LOAD_MORE_ITEMS,
    SET_SEARCH_VALUE,
    SET_SELECT_VALUE,
    SET_SELECT_CATEGORIES,
    RECEIVED_ITEMS,
};
