const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
const SET_SELECT_VALUE = 'SET_SELECT_VALUE';
const SET_SELECT_CATEGORIES = 'SET_SELECT_CATEGORIES';

export {
    SET_SEARCH_VALUE,
    SET_SELECT_VALUE,
    SET_SELECT_CATEGORIES,
};
