const SET_INPUT_VALUE = 'SET_INPUT_VALUE';
const SET_SELECT_CATEGORIES = 'SET_SELECT_CATEGORIES';

const RECEIVED_ITEMS = 'RECEIVED_ITEMS';
const REQUEST_ERROR = 'REQUEST_ERROR';
const IS_FETCHING = 'IS_FETCHING';

const LOAD_MORE_ITEMS = 'LOAD_MORE_ITEMS';

export {
    LOAD_MORE_ITEMS,
    SET_INPUT_VALUE,
    SET_SELECT_CATEGORIES,
    RECEIVED_ITEMS,
    REQUEST_ERROR,
    IS_FETCHING,
};
